wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.26
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.2
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 2
      4: 3.9.2
      5: 0.10.26
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 32
embedding_dims:
  desc: null
  value: 10
filters:
  desc: null
  value: 16
maxlen:
  desc: null
  value: 1000
vocab_size:
  desc: null
  value: 1000
